# Generated by Django 4.0.4 on 2022-05-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
